name: Lint

on:
  push:
    branches:
      - '**'

env:
  PHP_VERSION: '8.2'
  NODE_VERSION: '18'

jobs:
  php-lint:
    name: PHP Syntax Check & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: mbstring, dom, fileinfo, mysql
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check PHP syntax
        run: find app tests -name "*.php" -exec php -l {} \;

      - name: Laravel Pint
        run: vendor/bin/pint --test

      - name: PHPStan Static Analysis
        run: vendor/bin/phpstan analyse --error-format=github --memory-limit=256M

  node-lint:
    name: JavaScript/JSX Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.ts
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npm run code-quality
